"""Regenerate src/generated/*.jl from the Python sources of the JAX reference.

* tableaux.jl: the Diffrax Dopri8 tableau (deterministic arcs) and the XMDS2 RK9
  tableau of xmds2_rk9.py (stochastic arcs);
* cases.jl: every unit and boundary value the JAX script reads from a TestCase of
  cr3bp_deterministic_traj_opt.py, plus its equal-arc counts.

All numbers are written as round-trip float64 literals, so the Julia constants are
bitwise those of the reference. Run from the repository root:

    python madnlp_stochastic_traj_opt/tools/export_reference_data.py
"""

from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
TARGET = Path(__file__).resolve().parents[1] / "src" / "generated"
sys.path.insert(0, str(ROOT))

import diffrax  # noqa: E402
from xmds2_rk9 import XMDS2_RK9_TABLEAU  # noqa: E402
from cr3bp_deterministic_traj_opt import CASE_REGISTRY  # noqa: E402

# UNIFORM_ARCS_BY_CASE of cr3bp_stochastic_traj_opt_jax.py.
UNIFORM_ARCS_BY_CASE = {
    "lyapunov_l1_to_l2": 48,
    "nrho_l2_to_dro": 85,
    "halo_l2_to_halo_l1": 80,
}
CASE_SCALARS = (
    "mu", "length_unit", "time_unit", "velocity_unit", "thrust_unit",
    "m0_wet", "max_thrust_nd", "max_thrust_n", "exhaust_velocity_nd", "tof_nd",
)
HEADER = "# Generated by tools/export_reference_data.py. Do not edit."


def literal(value):
    return repr(float(value))


def vector(values):
    return "(" + ", ".join(literal(v) for v in values) + ",)"


def tableau_block(name, tableau):
    stages = len(tableau.b_sol)
    a = np.zeros((stages, stages))
    for i, row in enumerate(tableau.a_lower, start=1):
        a[i, : len(row)] = np.asarray(row, dtype=np.float64)
    lines = [f"const {name}_A = ("]
    lines += ["    " + vector(row) + "," for row in a]
    lines.append(")")
    lines.append(f"const {name}_B = {vector(tableau.b_sol)}")
    return "\n".join(lines)


def case_entry(case_id):
    case = CASE_REGISTRY[case_id]()
    fields = [f'id = "{case.test_case_id}"', f'display_name = "{case.display_name}"']
    fields += [f"{name} = {literal(getattr(case, name))}" for name in CASE_SCALARS]
    fields.append(f"x0_augmented = {vector(case.x0_augmented_state)}")
    fields.append(f"xf_state = {vector(case.xf_state)}")
    fields.append(f"uniform_arcs = {UNIFORM_ARCS_BY_CASE[case_id]}")
    return f'    "{case_id}" => (; ' + ", ".join(fields) + "),"


def write(name, lines):
    path = TARGET / name
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {path}")


def main():
    TARGET.mkdir(parents=True, exist_ok=True)
    write("tableaux.jl", [
        HEADER + f" Source: diffrax {diffrax.__version__}, xmds2_rk9.py.",
        "# Row i of *_A holds a[i, 1:i-1] (zero padded); *_B holds the solution weights.",
        tableau_block("DOPRI8", diffrax.Dopri8.tableau),
        tableau_block("XMDS2_RK9", XMDS2_RK9_TABLEAU),
    ])
    write("cases.jl", [
        HEADER + " Source: cr3bp_deterministic_traj_opt.py.",
        "const CASE_DATA = Dict(",
        *(case_entry(case_id) for case_id in UNIFORM_ARCS_BY_CASE),
        ")",
    ])


if __name__ == "__main__":
    main()
